file-explore:
  explore:
#    scan-path: C:\Example
    start-mode: new
  #Use to encoded JWT Token
  secret-key: Mine_Key...
  #No Use
  word2pdf:
    download-location: C:\Users\BabyPig\IdeaProjects\.tmp
    suffix: "系統預設"

server:
  port: 9090

spring:
  servlet:
    multipart:
      #50mb
      max-request-size: 52428800
      max-file-size: 52428800

  main:
    allow-circular-references: true

  mvc:
    view:
      prefix: /page
      suffix: .html
    log-request-details: true

  datasource:
#    username: root
#    password:
#    url: jdbc:mysql://localhost:3306/Explore?&createDatabaseIfNotExist=true
#
  jpa:
    show-sql: false
    generate-ddl: true
    properties:
      hibernate:
        format_sql: false
        metadata_builder_contributor: App.Init.InitHinernateParam
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  sql:
    init:
      # Add MySql Function
      schema-locations:
        - "classpath:sql/function.sql"
      mode: always
      separator: $$

  thymeleaf:
    cache: false
    enable-spring-el-compiler: true
    encoding: utf-8
    mode: HTML
    prefix: classpath:/static/page
    suffix: .html

