server:
  port: 9090

file-explore:
  explore:
    scan-path: C:\Users\BabyPig\IdeaProjects
    start-mode: non
    hide-path: true
  word2pdf:
    download-location: C:\Users\BabyPig\IdeaProjects\.tmp
    suffix: "系統預設"
  naming:
    tag:
      dir: Directory
      file: file
  inited: false

spring:
  servlet:
    multipart:
      #50mb
      max-request-size: 52428800
      max-file-size: 52428800

  main:
    allow-circular-references: true

  mvc:
    view:
      prefix: /page
      suffix: .html

  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/File_Detail?createDatabaseIfNotExist=true

  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: false
        metadata_builder_contributor: App.Init.Init
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  sql:
    init:
      schema-locations:
        - "classpath:sql/function.sql"
      mode: always
      separator: $$

  thymeleaf:
    cache: false
    enable-spring-el-compiler: true
    encoding: utf-8
    mode: HTML
    prefix: classpath:/static/page
    suffix: .html


